export const ACTION_GET_POSTS = 'ACTION_GET_POSTS'
export const ACTION_EDIT_POST = "ACTION_EDIT_POST"
export const ACTION_ADD_POST = "ACTION_ADD_POST"
export const ACTION_DELETE_POST = "ACTION_DELETE_POST"

export const ACTION_GET_TAGS = 'ACTION_GET_TAGS'
export const ACTION_EDIT_TAG = 'ACTION_EDIT_TAG'
export const ACTION_ADD_TAG = 'ACTION_ADD_TAG'
export const ACTION_DELETE_TAG = 'ACTION_DELETE_TAG'